### ISSUE TITLE
Dull pointer exception when list doesn't have a description

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine-ws-java#1]
https://github.com/intermine/intermine-ws-java/blob/master/main/src/org/intermine/webservice/client/lists/Lists.java#L49

We need a NULL check there, otherwise we get this error:
```
 > org.intermine.webservice.client.exceptions.ServiceException: Error
> parsing
> '{"dateCreated":"2015-07-09T14:09:40+0100","size":151,"authorized":false,"name":"AllGenes_GWAS","id":32000006,"type":"Gene","title":"AllGenes_GWAS","status":"CURRENT","timestamp":1436447380684,"tags":[]}'
> at org.intermine.webservice.client.lists.Lists.parseList(Lists.java:67)
> at
> org.intermine.webservice.client.services.ListService.processListsRequest(ListService.java:603)
> at
> org.intermine.webservice.client.services.ListService.getAccessibleLists(ListService.java:218)
> at
> t.viewer.server.intermine.IntermineServiceImpl.importLists(IntermineServiceImpl.scala:59)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ...
> Caused by: org.json.JSONException: JSONObject["description"] not found.
> at org.json.JSONObject.get(JSONObject.java:498)
> at org.json.JSONObject.getString(JSONObject.java:669)
> at org.intermine.webservice.client.lists.Lists.parseList(Lists.java:49)
> ... 34 more
> 
```

Example code:

```
package t.viewer.server.intermine;


import org.intermine.webservice.client.core.*;

import org.intermine.webservice.client.services.ListService;

import org.intermine.webservice.client.util.HttpConnection;

import org.json.JSONException;

import org.json.JSONObject;


public class IntermineTestApp {

  public static void main(String[] args) {

    String serviceUrl = "http://www.humanmine.org/humanmine/service";

    String appName = "humanmine";

    ServiceFactory sf = new ServiceFactory(serviceUrl);

    Service s = sf.getService("session", appName);

    Request r = s.createGetRequest(s.getUrl(), ContentType.APPLICATION_JSON);

    HttpConnection con = s.executeRequest(r);

    try {

      JSONObject resp = new JSONObject(con.getResponseBodyAsString());

      if (!resp.getBoolean("wasSuccessful")) {

        System.err.println("Unable to get session");

      }

      String token = resp.getString("token");

      ListService ls = sf.getListService();

      ls.setAuthentication(token);

      ls.getAccessibleLists();

    } catch (JSONException e) {

      // TODO Auto-generated catch block

      e.printStackTrace();

    }

  }

}


```

**Comment by danielabutano** [comment]
tested with the flymine list _esyN demo list_ and it works
