### ISSUE TITLE
Template examples aren't working

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine-ws-java#5]
I get this error when trying to get `Pathway_Genes` template:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Can't find class for class descriptor org.intermine.model.bio.RegulatoryRegion
        at org.intermine.template.xml.TemplateQueryBinding.unmarshalTemplates(TemplateQueryBinding.java:148)
        at org.intermine.client.services.TemplateService.getTemplates(TemplateService.java:233)
        at org.intermine.client.services.TemplateService.getTemplate(TemplateService.java:251)
        at samples.TemplateClient.main(TemplateClient.java:48)
Caused by: java.lang.RuntimeException: Can't find class for class descriptor org.intermine.model.bio.RegulatoryRegion
        at org.intermine.metadata.ClassDescriptor.getType(ClassDescriptor.java:174)
        at org.intermine.pathquery.PathQuery.buildSubclassMap(PathQuery.java:1852)
        at org.intermine.pathquery.PathQuery.verifyQuery(PathQuery.java:1417)
        at org.intermine.pathquery.PathQuery.isValid(PathQuery.java:1383)
        at org.intermine.pathquery.PathQueryHandler.endElement(PathQueryHandler.java:377)
        at org.intermine.template.xml.TemplateQueryHandler.endElement(TemplateQueryHandler.java:137)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
        at org.intermine.metadata.SAXParser.parse(SAXParser.java:59)
        at org.intermine.metadata.SAXParser.parse(SAXParser.java:42)
        at org.intermine.template.xml.TemplateQueryBinding.unmarshalTemplates(TemplateQueryBinding.java:145)
        ... 3 more
Caused by: java.lang.ClassNotFoundException: org.intermine.model.bio.RegulatoryRegion
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.intermine.metadata.ClassDescriptor.getType(ClassDescriptor.java:168)
        ... 22 more

``` 

`RegulatoryRegion` is in the local `genomic_model.xml` so not sure what this is about.

**Comment by danielabutano** [comment]
Not able to reproduce the error
